### ISSUE TITLE
WiFi cannot connect

### ISSUE THREAD

**Issue by rploeg** [SeeedJP/wioterminal-aziot-example#2]
Hi,

I have problem to connect with Wi-Fi, the screen stays on connecting to 'SSIDNAME'. I have succesfully changed the SSID and right password via the serialport (and with the set_az_ commands) It's unclear for me what files for Wi-Fi I I need to put on the WIO terminal. I have updated the Wi-Fi with the latest firmware of Seeed, but I saw that I need to use the zip file on this release page. I see in the zip file three files, do I need to copy them to the WIO for a working Wi-Fi?

**Comment by matsujirushi** [comment]
Hi @rploeg ,
Thanks for enjoy this example :-)
We need to update RTL firmware because Wi-Fi core separated main MPU. ([Info](https://www2.slideshare.net/TakashiMatsuoka2/wio-terminal/22))

Wouldn't this blog be helpful?
[The New Wio Terminal eRPC Firmware](https://www.hackster.io/Salmanfarisvp/the-new-wio-terminal-erpc-firmware-bfd8bd)

**Comment by rploeg** [comment]
Thanks! That did the job
